### leaflegend main ###

# Base function.

leaflegend = ->
  console.log "the coffeescript function definitions"
  true

# Version.
leaflegend.VERSION = '0.0.0'
# Export to the root, which is probably `window`.
root.leaflegend = leaflegend

# ---
# generated by js2coffee 2.0.0